version: "2"
services:
  agent_ip_checker:
    command: go run health_check_agent.go
    image: golang
    volumes:
        - .:/go
    ports:
        - "8082:8082"
    environment:
        - TCP_PORT=8082
  master_ip_checker:
    command: go run health_check_master.go
    image: golang
    volumes:
        - .:/go
    depends_on:
        - agent_ip_checker 
    environment:
        - agent_ips_num=1
        - agent_ip1=agent_ip_checker:8082
